name: Changelog
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  file_name: CHANGELOG.md

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: ${{ env.file_name }}

      - name: Commit changelog
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: '${{ env.file_name }}'
          message: 'Generate ${{ env.file_name }}'
          push: false

      - name: Open pull request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ github.token }}
          base: master
          branch: changelog/${{ github.event.pull_request.number }}
          title: "Generate CHANGELOG.md"
          signoff: true


